/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as StaffWaiterRouteImport } from './routes/staff.waiter'
import { Route as StaffTablesRouteImport } from './routes/staff.tables'
import { Route as StaffKitchenRouteImport } from './routes/staff.kitchen'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as SiteTrackRouteImport } from './routes/_site.track'
import { Route as SiteReservationRouteImport } from './routes/_site.reservation'
import { Route as SiteMenuRouteImport } from './routes/_site.menu'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as SiteAuthCallbackRouteImport } from './routes/_site.auth-callback'
import { Route as SiteAuthRouteImport } from './routes/_site.auth'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const StaffWaiterRoute = StaffWaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTablesRoute = StaffTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => StaffRoute,
} as any)
const StaffKitchenRoute = StaffKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => StaffRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const SiteTrackRoute = SiteTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReservationRoute = SiteReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMenuRoute = SiteMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAuthCallbackRoute = SiteAuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAuthRoute = SiteAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/auth': typeof SiteAuthRoute
  '/auth-callback': typeof SiteAuthCallbackRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/menu': typeof SiteMenuRoute
  '/reservation': typeof SiteReservationRoute
  '/track': typeof SiteTrackRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/staff/kitchen': typeof StaffKitchenRoute
  '/staff/tables': typeof StaffTablesRoute
  '/staff/waiter': typeof StaffWaiterRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof SiteAuthRoute
  '/auth-callback': typeof SiteAuthCallbackRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/menu': typeof SiteMenuRoute
  '/reservation': typeof SiteReservationRoute
  '/track': typeof SiteTrackRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/staff/kitchen': typeof StaffKitchenRoute
  '/staff/tables': typeof StaffTablesRoute
  '/staff/waiter': typeof StaffWaiterRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/_site/auth': typeof SiteAuthRoute
  '/_site/auth-callback': typeof SiteAuthCallbackRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/menu': typeof SiteMenuRoute
  '/_site/reservation': typeof SiteReservationRoute
  '/_site/track': typeof SiteTrackRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/staff/kitchen': typeof StaffKitchenRoute
  '/staff/tables': typeof StaffTablesRoute
  '/staff/waiter': typeof StaffWaiterRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/staff'
    | '/auth'
    | '/auth-callback'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/reservation'
    | '/track'
    | '/admin/customers'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reports'
    | '/staff/kitchen'
    | '/staff/tables'
    | '/staff/waiter'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth-callback'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/reservation'
    | '/track'
    | '/admin/customers'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reports'
    | '/staff/kitchen'
    | '/staff/tables'
    | '/staff/waiter'
    | '/'
    | '/admin'
    | '/staff'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/staff'
    | '/_site/auth'
    | '/_site/auth-callback'
    | '/_site/cart'
    | '/_site/checkout'
    | '/_site/menu'
    | '/_site/reservation'
    | '/_site/track'
    | '/admin/customers'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reports'
    | '/staff/kitchen'
    | '/staff/tables'
    | '/staff/waiter'
    | '/_site/'
    | '/admin/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/staff/waiter': {
      id: '/staff/waiter'
      path: '/waiter'
      fullPath: '/staff/waiter'
      preLoaderRoute: typeof StaffWaiterRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/tables': {
      id: '/staff/tables'
      path: '/tables'
      fullPath: '/staff/tables'
      preLoaderRoute: typeof StaffTablesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/kitchen': {
      id: '/staff/kitchen'
      path: '/kitchen'
      fullPath: '/staff/kitchen'
      preLoaderRoute: typeof StaffKitchenRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/track': {
      id: '/_site/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof SiteTrackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reservation': {
      id: '/_site/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof SiteReservationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/menu': {
      id: '/_site/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof SiteMenuRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/auth-callback': {
      id: '/_site/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof SiteAuthCallbackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/auth': {
      id: '/_site/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof SiteAuthRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAuthRoute: typeof SiteAuthRoute
  SiteAuthCallbackRoute: typeof SiteAuthCallbackRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteMenuRoute: typeof SiteMenuRoute
  SiteReservationRoute: typeof SiteReservationRoute
  SiteTrackRoute: typeof SiteTrackRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAuthRoute: SiteAuthRoute,
  SiteAuthCallbackRoute: SiteAuthCallbackRoute,
  SiteCartRoute: SiteCartRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteMenuRoute: SiteMenuRoute,
  SiteReservationRoute: SiteReservationRoute,
  SiteTrackRoute: SiteTrackRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffKitchenRoute: typeof StaffKitchenRoute
  StaffTablesRoute: typeof StaffTablesRoute
  StaffWaiterRoute: typeof StaffWaiterRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffKitchenRoute: StaffKitchenRoute,
  StaffTablesRoute: StaffTablesRoute,
  StaffWaiterRoute: StaffWaiterRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
